trigger: none # Do not build branches on push.

pr:
- master

schedules:
- cron: "0 2 * * *"
  displayName: Nightly build
  branches:
    include:
    - master
  always: true # Also build if there were no code changes, because many of our tests rely on external infrastructure.

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  # Tool versions.
  BOWER_VERSION: '1.8.8'
  BUNDLER_VERSION: '2.1.4'
  COMPOSER_VERSION: '5.1.0' # The version refers to the installer, not to Composer.
  CONAN_VERSION: '1.18.0'
  FLUTTER_VERSION: 'v1.12.13+hotfix.9-stable'
  GO_DEP_VERSION: '0.5.4'
  PYTHON_PIPENV_VERSION: '2018.11.26'
  RUST_VERSION: '1.35.0'
  STACK_VERSION: '2.1.3.20190715'
  VIRTUALENV_VERSION: '20.0.14'

stages:
- stage: run
  displayName: Run
  jobs:
  - template: .azure-pipelines/docker.yml
  - template: .azure-pipelines/detekt.yml
  - template: .azure-pipelines/linux-test.yml
  - template: .azure-pipelines/linux-analyzer-test.yml
  - template: .azure-pipelines/windows-test.yml
  - template: .azure-pipelines/windows-analyzer-test.yml
