curations:
  license_findings:
  - path: "spdx-utils/src/main/kotlin/SpdxLicense.kt"
    comment: "This file defines official SPDX.org licenses so they can be used in OSS Review Toolkit."
    reason: "DATA_OF"
    concluded_license: "Apache-2.0"
  - path: "spdx-utils/src/main/resources/licenses/**"
    comment: "This directory contains all official SPDX.org license ids which are used to generate open source notices. \
      SPDX and ScanCode license files are licensed under CC0-1.0, see \
      https://github.com/spdx/license-list-XML/blob/master/package.json#L33"
    reason: "DATA_OF"
    concluded_license: "CC0-1.0"
  - path: "spdx-utils/src/main/resources/licensesrefs/**"
    comment: "This directory contains all non-official SPDX license ids which are used to generate open source notices. \
      SPDX and ScanCode license files are licensed under CC0-1.0, see \
      https://github.com/spdx/license-list-XML/blob/master/package.json#L33 \
      https://github.com/nexB/scancode-toolkit/blame/develop/README.rst#L168"
    reason: "DATA_OF"
    concluded_license: "CC0-1.0"
  - path: "analyzer/src/funTest/assets/projects/synthetic/php-composer/{empty-des, lockfile, no-deps, with-provide, with-replace}/composer.phar"
    comment: "This file 'composer.phar' is part of PHP Composer and includes a mapping from human readable strings to SPDX license ids."
    reason: "DATA_OF"
    concluded_license: "MIT"
excludes:
  paths:
  - pattern: "*/src/{funTest,test}/**"
    reason : "TEST_TOOL_OF"
    comment: "Licenses contained in this directory are used for testing and do not apply to the OSS Review Toolkit."
  - pattern: "reporter-web-app/src/config.js"
    reason : "DATA_FILE_OF"
    comment: "This file contains license data used in the web app report. Contained licenses do not apply to the OSS Review Toolkit."
  - pattern: "reporter-web-app/src/data/choosealicense/**"
    reason : "DATA_FILE_OF"
    comment: "This file contains license data used in the web app report. Contained licenses do not apply to the OSS Review Toolkit."
  - pattern: "spdx-utils/src/main/resources/{exceptions,licenserefs,licenses}/**"
    reason : "DATA_FILE_OF"
    comment: "This license file is used for generating license notes and does not apply to the OSS Review Toolkit."
  - pattern: "spdx-utils/src/main/kotlin/{SpdxDeclaredLicenseMapping,SpdxLicense,SpdxLicenseAliasMapping,SpdxLicenseException}.kt"
    reason : "DATA_FILE_OF"
    comment: "Licenses contained in this class are used for processing licenses and do not apply to the OSS Review Toolkit."
  - pattern: "test-utils/**"
    reason : "TEST_TOOL_OF"
    comment: "Licenses contained in this directory are used for testing and do not apply to the OSS Review Toolkit."
  scopes:
  - name   : "devDependencies"
    reason : "BUILD_TOOL_OF"
    comment: "Scope with dependencies only used for development. Not included in released artifacts in the context of this project."
  - name   : "(test.*|funTest.*)"
    reason : "TEST_TOOL_OF"
    comment: "Scope with dependencies only used for testing. Not included in released artifacts in the context of this project."
resolutions:
  errors:
  - message: "ERROR: Timeout after 300 seconds while scanning file 'reporter-web-app/public/index.html'."
    reason : "SCANNER_ISSUE"
    comment: "The error can be ignored because the file does contain relevant license information."
  - message: "ERROR: Timeout after 300 seconds while scanning file 'scanner/src/test/assets/aws-java-sdk-core-1.11.160_scancode-2.9.7.json'."
    reason : "SCANNER_ISSUE"
    comment: "This file contains test data. Contained licenses do not apply to the OSS Review Toolkit."
