language: java

matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk10
      env: ANDROID_SDK_ARCHIVE="sdk-tools-linux-4333796.zip"
    - os: osx
      osx_image: xcode10
      env: ANDROID_SDK_ARCHIVE="sdk-tools-darwin-4333796.zip"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.ivy2
    - $HOME/.m2/repository/
    - $HOME/.ort/analyzer/cache/http
    - $HOME/.ort/analyzer/cache/remote_artifacts
    - $HOME/.ort/downloader/cache/http
    - $HOME/.ort/scanner/cache/http

env:
  global:
    - ANDROID_HOME="/opt/android"
    - GIMME_GO_VERSION="1.10"
    - DEP_RELEASE_TAG="v0.4.1"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo rm -f $JAVA_HOME/lib/security/cacerts;
      sudo ln -s /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts;
    fi

install:
  - npm install -g bower@1.8.8 npm@6.4.0 yarn@1.13.0 # Need to run this before brew to avoid "dyld: Library not loaded".
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      exit;
      sudo apt install -y cvs;
      eval "$(gimme)";
      curl https://raw.githubusercontent.com/golang/dep/7d5cd199ce454707f81c63b7ea4299151b8b981d/install.sh | sh;
      phpenv global 7.1.19;
      curl -Ls https://git.io/sbt > ~/bin/sbt;
      chmod a+x ~/bin/sbt;
    else
      mkdir ~/bin;
      brew install php71 sbt;
    fi
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - curl -Os https://dl.google.com/android/repository/$ANDROID_SDK_ARCHIVE
  - sudo unzip -q $ANDROID_SDK_ARCHIVE -d $ANDROID_HOME
  - sudo chmod a+x $ANDROID_HOME/tools/bin/sdkmanager
  - export SDKMANAGER_OPTS="--add-modules java.xml.bind"
  - yes | $ANDROID_HOME/tools/bin/sdkmanager --verbose "platform-tools"

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      exit;
    fi
  - set -o pipefail
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      ./gradlew --no-daemon --stacktrace :cli:dockerBuildImage;
      ./gradlew --no-daemon --stacktrace -Dkotlintest.tags.exclude=ScanCodeTag check jacocoReport | tee log.txt;
    else
      ./gradlew --no-daemon --stacktrace -Dkotlintest.tags.exclude=ExpensiveTag check jacocoReport | tee log.txt;
    fi
  - if grep -A1 ".+Test.+STARTED$" log.txt | grep -q "^:"; then
      echo "Some tests seemingly have been aborted.";
      exit 1;
    fi

after_success:
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      bash <(curl -s https://codecov.io/bash) -X gcov -f '!*/src/*/assets/*'
    fi
