environment:
  HOME: $(HOMEDRIVE)$(HOMEPATH)

cache:
  - $(HOME)\.gradle\caches\jars-1
  - $(HOME)\.gradle\caches\jars-2
  - $(HOME)\.gradle\caches\jars-3
  - $(HOME)\.gradle\caches\modules-2
  - $(HOME)\.gradle\caches\transforms-1
  - $(HOME)\.gradle\wrapper\dists
  - $(HOME)\.ivy2
  - $(HOME)\.m2\repository
  - $(HOME)\.ort\analyzer\cache\remote_artifacts
  - $(HOME)\.ort\analyzer\cache\http
  - $(HOME)\.ort\scanner\cache\http

install:
  - git submodule update --init --recursive
  - npm install -g npm@5.5.1 yarn@1.3.2
  - pip install virtualenv==15.1.0
  - cinst sbt --version 1.0.2 -y
  - choco install php --version 7.2.0
  - cd c:\tools\php72
  - echo extension=php_openssl.dll >> php.ini
  - copy php.ini-production php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - refreshenv

build_script:
  - gradlew assemble

test_script:
  - gradlew -DexcludeTags=Expensive --stacktrace check

on_finish:
  - gradlew --stop # Fix "fileHashes.bin" being used by another process.
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $pattern = '**\build\test-results\**\TEST-*.xml'
      foreach ($file in (Resolve-Path $pattern)) {
        (New-Object 'System.Net.WebClient').UploadFile($url, $file)
      }
