excludes:
  scopes:
  - pattern: "require-dev"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Scope with dependencies only used for development. Not included in released artifacts in the context of this project."
