excludes:
  projects:
  - path: "analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/npm/package.json"
    type: "OTHER"
    reason: "OTHER"
    comment: "Project not delivered."
  - path: "analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/gradle/app1/build.gradle"
    type: "OTHER"
    scopes:
    - name: "testAnnotationProcessor"
      reason: "OTHER"
      comment: "Test dependencies."
    - name: "testCompile"
      reason: "OTHER"
      comment: "Test dependencies."
    - name: "testCompileClasspath"
      reason: "OTHER"
      comment: "Test dependencies."
    - name: "testCompileOnly"
      reason: "OTHER"
      comment: "Test dependencies."
    - name: "testRuntime"
      reason: "OTHER"
      comment: "Test dependencies."
    - name: "testRuntimeClasspath"
      reason: "OTHER"
      comment: "Test dependencies."
  scopes:
  - name: "archives"
    reason: "OTHER"
    comment: "Scope not published."
