excludes:
  projects:
  - path: "analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/npm/package.json"
    reason: "OTHER"
    comment: "Project not delivered."
  - path: "analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/gradle/app1/build.gradle"
    scopes:
    - name: "testAnnotationProcessor"
      reason: "OTHER"
      comment: "Test dependencies."
    - name: "testCompile"
      reason: "OTHER"
      comment: "Test dependencies."
    - name: "testCompileClasspath"
      reason: "OTHER"
      comment: "Test dependencies."
    - name: "testCompileOnly"
      reason: "OTHER"
      comment: "Test dependencies."
    - name: "testRuntime"
      reason: "OTHER"
      comment: "Test dependencies."
    - name: "testRuntimeClasspath"
      reason: "OTHER"
      comment: "Test dependencies."
    packages:
    - id: "Maven:org.apache.commons:commons-text:1.1"
      reason: "OTHER"
      comment: "Undelivered dependency."
  - path: "analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/gradle/app2/build.gradle"
    errors:
    - message: ".*Could not find org.example:another-nonexistent-package:1.0.*"
      reason: "OTHER"
      comment: "Undelivered dependency."
  - path: "analyzer/src/funTest/assets/projects/synthetic/project-with-excludes/maven/broken1/pom.xml"
    errors:
    - message: ".*The groupId cannot be empty."
      reason: "OTHER"
      comment: "Undelivered project."
  scopes:
  - name: "archives"
    reason: "OTHER"
    comment: "Scope not published."
  packages:
  - id: "Maven:org.apache.commons:commons-lang3:3.5"
    reason: "OTHER"
    comment: "Undelivered dependency."
  errors:
  - message: "Unresolved: ModuleVersionNotFoundException: Could not find org.example:nonexistent-package:1.0.*"
    reason: "OTHER"
    comment: "Undelivered dependency."
  - message: ".*The artifactId cannot be empty."
    reason: "OTHER"
    comment: "Undelivered project."
