jobs:
# TODO: Consider running the Docker job only if the Dockerfile was changed.
- job: 'Docker'
  pool:
    vmImage: 'ubuntu-18.04'
  # TODO: Add caching.
  steps:
  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: 'Dockerfile'
      tags: |
        ort
