name: Validate Gradle Wrapper

on: pull_request

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Validate Wrapper
      uses: gradle/wrapper-validation-action@master
