name: Validate Gradle Wrapper

on:
  pull_request:
    paths:
    - '**/gradle-wrapper.*'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Validate Wrapper
      uses: gradle/wrapper-validation-action@v1
