name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Action
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Markdown Check Action
      uses: gaurav-nelson/github-action-markdown-link-check@master
      with:
        check-modified-files-only: yes
        max-depth: 2
        use-quiet-mode: yes
