name: Automatic Rebase

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != null && github.event.comment.body == '/rebase'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Action
      uses: actions/checkout@master
    - name: Rebase Action
      uses: docker://cirrusactions/rebase:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
