name: Static Analysis

on: pull_request

jobs:
  detekt:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Check for Detekt Issues
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: --no-daemon --stacktrace detekt
    - name: Upload SARIF File
      uses: github/codeql-action/upload-sarif@v1
      if: ${{ always() }} # Upload even if the previous step failed.
      with:
        sarif_file: build/reports/detekt/merged.sarif
